blueprint:
  name: Turn On Area
  description: Turn on all visible fans, lights, and switches in a given area.
  author: Cory Charlton
  source_url: https://github.com/CCSWE-Home-Assistant/blueprints/script/turn_on_area.yaml
  domain: script
  input:
    area_id:
      name: Area
      selector:
        area:
    include_fans:
      name: Include Fans
      selector:
        boolean:
      default: true
    include_lights:
      name: Include Lights
      selector:
        boolean:
      default: true
    include_switches:
      name: Include Switches
      selector:
        boolean:
      default: true

mode: restart
max_exceeded: silent

variables:
  include_fans: !input include_fans
  include_lights: !input include_lights
  include_switches: !input include_switches

sequence:
  - if:
      - condition: template
        value_template: "{{ include_fans }}"
    then:
      - alias: "Turn On Fans"
        action: fan.turn_on
        target:
          area_id: !input area_id
  - if:
      - condition: template
        value_template: "{{ include_lights }}"
    then:
      - alias: "Turn On Lights"
        action: light.turn_on
        target:
          area_id: !input area_id
  - if:
      - condition: template
        value_template: "{{ include_lights }}"
    then:
      - alias: "Turn On Switches"
        action: switch.turn_on
        target:
          area_id: !input area_id
