blueprint:
  name: Automatically turn off light.
  description: Automatically turn off light after a delay.
  author: Cory Charlton
  source_url: https://github.com/CCSWE-Home-Assistant/blueprints/automation/auto_turn_off_light.yaml
  domain: automation
  input:
    light_entity:
      name: Light
      selector:
        entity:
          filter:
            - domain: light
    delay_minutes:
      name: Delay time
      description: Time to wait before turning off the light.
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

variables:
  light_entity: !input light_entity

triggers:
  - trigger: state
    entity_id: !input light_entity
    not_from:
      - "unavailable"
      - "unknown"
    to:
      - "on"

action:
  - wait_for_trigger:
      - trigger: state
        entity_id: !input light_entity
        to: "off"
    timeout:
      hours: 0
      minutes: !input delay_minutes
      seconds: 0
      milliseconds: 0
  - if:
      - condition: template
        value_template: "{{ is_state(light_entity, 'on') }}"
    then:
      - action: light.turn_off
        data:
          entity_id: !input light_entity
