blueprint:
  name: Automatically turn off lights.
  description: Automatically turn off lights after a delay.
  author: Cory Charlton
  source_url: https://github.com/CCSWE-Home-Assistant/blueprints/automation/auto_turn_off_light.yaml
  domain: automation
  input:
    light_entities:
      name: Lights
      selector:
        entity:
          filter:
            - domain: light
          multiple: true
    delay_minutes:
      name: Delay time
      description: Time to wait before turning off the light.
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

variables:
  light_entities: !input light_entities

triggers:
  - trigger: state
    entity_id: !input light_entities
    not_from:
      - "unavailable"
      - "unknown"
    to:
      - "off"
      - "on"

action:
  - if:
      - condition: template
        value_template: "{{ expand(light_entities) | selectattr('state', 'eq', 'on') | list | count > 0 }}"
    then:
      - delay:
          hours: 0
          minutes: !input delay_minutes
          seconds: 0
          milliseconds: 0
  - if:
      - condition: template
        value_template: "{{ expand(light_entities) | selectattr('state', 'eq', 'on') | list | count > 0 }}"
    then:
      - action: light.turn_off
        data:
          entity_id: !input light_entities
