blueprint:
  name: Synchronize Light and Light
  description: Synchronize light with light.
  author: Cory Charlton
  source_url: https://github.com/CoryCharlton/home-assistant-blueprints/automation/synchronize_light_light.yaml
  domain: automation
  input:
    light_entity_1:
      name: Light 1
      selector:
        entity:
          filter:
            - domain: light
    light_entity_2:
      name: Light 2
      selector:
        entity:
          filter:
            - domain: light

mode: restart
max_exceeded: silent

variables:
  light_entity_1: !input light_entity_1
  light_entity_2: !input light_entity_2

triggers:
  - trigger: state
    entity_id: !input light_entity_1
  - trigger: state
    entity_id: !input light_entity_1
    attribute: brightness

  - trigger: state
    entity_id: !input light_entity_2
  - trigger: state
    entity_id: !input light_entity_2
    attribute: brightness

action:
  - choose:
      - conditions:
          condition: template
          value_template: "{{ is_state(trigger.to_state.entity_id, 'on') }}"
        sequence:
          - action: light.turn_on
            data:
              brightness: "{{ state_attr(trigger.to_state.entity_id, 'brightness') }}"
              entity_id: "{% if trigger.from_state.entity_id == light_entity_1 %} {{ light_entity_2 }} {% else %} {{ light_entity_1 }} {% endif %}"
      - conditions:
          condition: template
          value_template: "{{ is_state(trigger.to_state.entity_id, 'off') }}"
        sequence:
          - action: light.turn_off
            data:
              entity_id: "{% if trigger.from_state.entity_id == light_entity_1 %} {{ light_entity_2 }} {% else %} {{ light_entity_1 }} {% endif %}"
